#! /usr/bin/env zsh

read -p "Do you want to install Azure CLI? " -n 1 -r -t 15
if [[ $REPLY =~^[Yy]$ ]]; then
	sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc

	sudo sh -c 'echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'

	sudo yum install azure-cli
fi
