#! /usr/bin/env zsh

read -p "?Do you want to install Azure CLI? " -q
if [[ $REPLY == "y" ]]; then
	sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc

	sudo sh -c 'echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'

	sudo yum install azure-cli
fi
