" XDG support
if empty($MYVIMRC) | let $MYVIMRC = expand('<sfile>:p') | endif

if empty($XDG_CACHE_HOME)  | let $XDG_CACHE_HOME  = $HOME."/.cache"       |
endif
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME."/.config"      |
endif
if empty($XDG_DATA_HOME)   | let $XDG_DATA_HOME   = $HOME."/.local/share" |
endif

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p', 0700)
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p', 0700)

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p', 0700)
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p', 0700)
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p', 0700)

if !has('nvim') " Neovim has its own special location
  set viminfofile=$XDG_CACHE_HOME/vim/viminfo
endif

set nocompatible
filetype off

" fuzzy finder
set rtp+=$FZF_HOME

" Plugins will be downloaded under the specified directory.
call plug#begin('$XDG_DATA_HOME/vim/plugins')

" Declare the list of plugins.
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'NLKNguyen/papercolor-theme'
Plug 'aklt/plantuml-syntax'
Plug 'blueyed/vim-diminactive'
Plug 'bronson/vim-trailing-whitespace'
Plug 'dense-analysis/ale'
Plug 'editorconfig/editorconfig-vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'sirtaj/vim-openscad'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Set leader shortcut to a comma ','. By default it's the backslash
let mapleader = " "

""""""""""""""""""""""
"      Settings      "
""""""""""""""""""""""
set nocompatible                " Enables us Vim specific features
filetype off                    " Reset filetype detection first ...
filetype plugin indent on       " ... and enable filetype detection
if has("nvim") == 0
	set ttyfast                     " Indicate fast terminal conn for faster redraw
	set ttymouse=xterm2             " Indicate terminal type for mouse codes
	set ttyscroll=3                 " Speedup scrolling
else
	set inccommand=nosplit          " show previews inline
endif
set laststatus=2                " Show status line always
set encoding=utf-8              " Set default encoding to UTF-8
set autoread                    " Automatically read changed files
set autoindent                  " Enabile Autoindent
set backspace=indent,eol,start  " Makes backspace key more powerful.
set incsearch                   " Shows the match while typing
set hlsearch                    " Highlight found searches
set noerrorbells                " No beeps
set number norelativenumber	" Show line numbers
set showcmd                     " Show me what I'm typing
set noswapfile                  " Don't use swapfile
set nobackup                    " Don't create annoying backup files
set splitright                  " Vertical windows should be split to right
set splitbelow                  " Horizontal windows should split to bottom
set autowrite                   " Automatically save before :next, :make etc.
set hidden                      " Buffer should still exist if window is closed
set fileformats=unix,dos,mac    " Prefer Unix over Windows over OS 9 formats
set noshowmatch                 " Do not show matching brackets by flickering
set ignorecase                  " Search case insensitive...
set smartcase                   " ... but not it begins with upper case
set completeopt=menu,menuone    " Show popup menu, even if there is one entry
set pumheight=10                " Completion window max size
set nocursorcolumn              " Do not highlight column (speeds up highlighting)
set nocursorline                " highlight cursor line
set lazyredraw                  " Wait to redraw
set nomodeline                  " disable mode line I don't use and it has vulnerability
set scrolloff=3	                " minimum 10 lines around cursor when jumping

" This enables us to undo files even if you exit Vim.
if has('persistent_undo')
  set undofile
  set undodir=~/.config/vim/tmp/undo//
endif

" Colorscheme
syntax enable
set background=dark
colorscheme PaperColor

" visible whitespace
set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:␣
set nolist                      " hide whitespace
highlight SpecialKey ctermfg=220       " override color to yellow

"highlight active split by enabling syntax higlighting
let g:diminactive_use_syntax = 0
let g:diminactive_use_colorcolumn = 1

"  """"""""""""""""""""""
"  Mappings      "
"  """"""""""""""""""""""
"<C-s> to save
noremap <silent> <C-s> :update<CR>
vnoremap <silent> <C-s> <C-C>:update<CR>
inoremap <silent> <C-s> <Esc>:update<CR>

" clear search highlights
map <leader>l :nohlsearch<CR>

"q to quit buffer
map <leader>q :q<CR>

"split motions to simple <C-h|j|k|l>
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-h> <C-w>h
map <C-l> <C-w>l

" allow the . to execute once for each line of a visual selection
vnoremap . :normal .<CR>

"toggle whitespace
nnoremap <leader>w :set list!<CR>

""Move up and down by displayed lines (e.g. don't skip through a wrapped line)
noremap <Up> gk
noremap <Down> gj
noremap j gj
noremap k gk

" Act like D and C
nnoremap Y y$

" repeat macro
nnoremap Q @@

" vim window motions
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" run the current line as a command
nnoremap <leader>e :exe getline(line('.'))<cr>

" reduce updatetime for prompt git gutter
set updatetime=250

" allow the . to execute once for each line of a visual selection
vnoremap . :normal .<CR>

" double leader to enter ex mode
nnoremap <silent> <leader><leader> :
vnoremap <silent> <leader><leader> :

" fzf mappings
nnoremap <silent> <leader>o :Files<CR>
nnoremap <silent> <leader>O :Files!<CR>
cnoremap <silent> <C-p> :History:<CR>
cnoremap <silent> <C-_> <ESC>:History/<CR>
nnoremap <silent> <leader>y :History<CR>
nnoremap <silent> <leader>b :Buffers<CR>
nnoremap <silent> <leader>` :Marks<CR>
nnoremap <silent> <leader>L :BLines<CR>
nnoremap <silent> <F1> :Helptags<CR>
inoremap <silent> <F1> <ESC>:Helptags<CR>
noremap <silent> <leader>; :Commands<CR>
inoremap <silent> <F3> <ESC>:Snippets<CR>
nnoremap <silent> <leader>f :Ag<CR>
noremap <silent> <leader>s yiw:Ag <C-r>"<CR>

" Fugitive Conflict Resolution
nnoremap <leader>gd :Gvdiff<CR>
nnoremap gdh :diffget //2<CR>
nnoremap gdl :diffget //3<CR>

" source ~/.vim/coc.vim
